# Generated by Django 3.2.3 on 2021-10-30 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0003_alter_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.IntegerField()),
                ('comentario', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, default='', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion_usuario', to='movies_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, default='', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_usuario', to='movies_api.usuario')),
            ],
        ),
    ]
